version: "2.1"
services:
#  app:
#    build:
#      context: .
#    command: npm run start
#    ports:
#      - 4000:4000
#    environment:
#      PORT: 4000
#      NODE_ENV: development
#      DB_HOST: database
#      DB_PORT: 5432
#      DB_DATABASE_NAME: monterail
#      DB_USERNAME: monterail
#      DB_PASSWORD: password
#      JWT_SECRET: secret
#    depends_on:
#      - migration
#      - database
#
#  migration:
#    build:
#      context: .
#    command: npm run migration:run
#    depends_on:
#      - database
#    environment:
#      DB_HOST: database
#      DB_PORT: 5432
#      DB_DATABASE_NAME: monterail
#      DB_USERNAME: monterail
#      DB_PASSWORD: password

  database:
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monterail
      POSTGRES_USER: monterail
      POSTGRES_PASSWORD: password
    logging:
      driver: none

volumes:
  build:
  node_modules:
  pgdata:
